/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WiiMonitor.java
 *
 * Created on Dec 3, 2008, 5:00:41 PM
 */

package org.rmutl.tresshy.monitor;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import wiiremotej.IRLight;
import wiiremotej.WiiRemote;
import wiiremotej.WiiRemoteJ;
import wiiremotej.event.WRIREvent;
import wiiremotej.event.WRStatusEvent;
import org.rmutl.tresshy.WiiDataHandler;

/**
 *
 * @author catchajaa
 */
public class WiiMonitor extends javax.swing.JFrame {

    /** Creates new form WiiMonitor */
    public WiiMonitor( final WiiRemote remote ) {
        initComponents();
        try {
           
            remote.addWiiRemoteListener(new WiiDataHandler(remote) {

                @Override
                public void battery(WRStatusEvent evt) {
                    System.out.println("\n Status:"+ evt.getBatteryLevel());
                }

                @Override
                public void wiimote(IRLight linght, double x, double y, double size) {
                    jLabel1.setLocation((int)(x*640),320 -(int)(y*320));
                }
            });
            remote.setIRSensorEnabled(true, WRIREvent.BASIC);
            remote.setLEDIlluminated(0, true);
            new Thread(new Runnable() {
			public void run() {
				while (true) {
					try {
						// triggers #statusReported(WRStatusEvent)
						if (remote.isConnected())
							remote.requestStatus();
					} catch (Exception e) {
						e.printStackTrace();
					//	WiimoteWhiteboard.getLogger().log(Level.WARNING, "Error on requesting status from Wii Remote", e);
					}
					try {
						Thread.sleep(60 * 1000);
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}
			}
		}).start();
        } catch (IOException ex) {
            Logger.getLogger(WiiDataHandler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(WiiDataHandler.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(WiiDataHandler.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                MonitorClose(evt);
            }
        });

        jLabel1.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(638, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-740)/2, (screenSize.height-420)/2, 740, 420);
    }// </editor-fold>//GEN-END:initComponents

    private void MonitorClose(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_MonitorClose
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_MonitorClose

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
